apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app: node-app # The name should be same as the name while creating pod.
  ports:
    - port: 80
      targetPort: 3000 # This is the port where your actual application runs.
      nodePort: 30007 # The port you want to assign to run app in local machine.
