apiVersion: v1
kind: Secret
metadata:
  name: mongo-secrets
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: "YWRtaW4K" # Here the data is converted to base64 not for security
# reason but the secret is stored in binary which is beneficial for accssing through the pod
  MONGO_INITDB_ROOT_PASSWORD: "cGFzc3dvcmQ="