apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: my-image
    volumeMounts:
    - name: mongo-secrets-volume
      mountPath: /etc/secrets # the file which contains the secrets is inside the container in this pod
      readOnly: true
  volumes:
  - name: mongo-secrets-volume
    secret:
      secretName: mongo-secrets # the name must match the metadata name of secrets.