# THis method is used to to get specific value from the secrets.yaml file.

apiVersion: v1
kind: Pod
metadata:
  name: mongo-secrets
spec:
  containers:
  - name: mongo-container
    image: mongo:4.4
    env:
    - name: MONGO_USER
      valueFrom:
        secretKeyRef:
          name: mongo-secrets
          key: MONGO_INITDB_ROOT_USERNAME
    - name: MONGO_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mongo-secrets
          key: MONGO_INITDB_ROOT_PASSWORD