apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
# Here, livenesss probe is done to check is port 80 is open and can access / path
# that is http://localhost:80/, if we put any random value in either path or poth,
# the liveness probe will give warning of unhealthy container.
# That warning will be logged inorder to check it.
