apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  capacity:
    storage: 3Gi
  accessModes:
  - ReadWriteMany
  local:
    path: /storage/data # create this folder in minikube using ssh so no errors appears
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minikube